In [2]:
import pandas as pd
import numpy as np
import nltk
#nltk.download()
from nltk.corpus import stopwords

In [3]:
test = pd.read_csv('dataset/test.csv')
train = pd.read_csv('dataset/train.csv')

In [4]:
train

,id,raw_address,POI/street
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika
1,1,"aye, jati sampurna",/
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung
3,3,"toko dita, kertosono",toko dita/
4,4,jl. orde baru,/jl. orde baru
...,...,...,...
299995,299995,jend ahmad yani 331 kertasari ciamis,/jend ahmad yani
299996,299996,"raya cila kko, cilandak timur kel.",/raya cila kko
299997,299997,tanjung gusta jl. yaya 2 no 17,/
299998,299998,jalan cipadu jaya taman asri gang bijaksana 3 ...,taman asri/
299999,299999,jaya maspion permata blok beryl b2 no.58,jaya maspion permata/

In [18]:
test

          id                                        raw_address
0          0              s. par 53 sidanegara 4 cilacap tengah
1          1              angg per, baloi indah kel. lubuk baja
2          2                              asma laun, mand imog,
3          3      ud agung rej, raya nga sri wedari karanganyar
4          4                         cut mutia, 35 baiturrahman
...      ...                                                ...
49995  49995                    toko mbak farid semboro semboro
49996  49996     vie - tk. ridho kids, vete 3 cari, 16720 ciawi
49997  49997                mart dan roti bakar malabar, nasio,
49998  49998  graha indah pamulang jl. mujair raya bambu apu...
49999  49999                                               adi,

[50000 rows x 2 columns]

In [5]:
train[['POI', 'street']] = train['POI/street'].str.split('/', 1, expand=True)
train['POI/street'].replace('/', np.nan, inplace=True)
train['POI'].replace('', np.nan, inplace=True)
train['street'].replace('', np.nan, inplace=True)
train.head()

,id,raw_address,POI/street,POI,street
0,0,jl kapuk timur delta sili iii lippo cika 11 a ...,/jl kapuk timur delta sili iii lippo cika,NaN,jl kapuk timur delta sili iii lippo cika
1,1,"aye, jati sampurna",NaN,NaN,NaN
2,2,setu siung 119 rt 5 1 13880 cipayung,/siung,NaN,siung
3,3,"toko dita, kertosono",toko dita/,toko dita,NaN
4,4,jl. orde baru,/jl. orde baru,NaN,jl. orde baru

In [6]:
def missing_value_of_data(data):
    total = data.isnull().sum().sort_values(ascending=False)
    percentage = round(total/data.shape[0]*100,2)
    return pd.concat([total,percentage], axis=1, keys=['Total','Percentage'])

In [8]:
print('Missing Value:')
missing_value_of_data(train)

Missing Value:

              Total  Percentage
POI          178509       59.50
street        70143       23.38
POI/street    31993       10.66
raw_address       0        0.00
id                0        0.00

In [8]:
train_clean = train.dropna()

In [9]:
train_clean

,id,raw_address,POI/street,POI,street
5,5,"raya samb gede, 299 toko bb kids",toko bb kids/raya samb gede,toko bb kids,raya samb gede
10,10,"cikahuripan sd neg boj 02 klap boj, no 5 16877",sd negeri bojong 02/klap boj,sd negeri bojong 02,klap boj
27,27,"jln.tirta tawar, br. junjungan, ubud, barat ja...",br. junjungan/jln.tirta tawar,br. junjungan,jln.tirta tawar
31,31,"jl. amd, komplek borneo lestari, blok 2, no. 30",komplek borneo lestari/jl. amd,komplek borneo lestari,jl. amd
48,48,"rumah makan pela, raya jomb,",rumah makan pelangi/raya jomb,rumah makan pelangi,raya jomb
...,...,...,...,...,...
299970,299970,"anggun jewellery, mangga dua raya, no 6 rw 5",anggun jewellery/mangga dua raya,anggun jewellery,mangga dua raya
299974,299974,"islamic training cen pare, brawi, pelem pare",islamic training center pare/brawi,islamic training center pare,brawi
299983,299983,"la banda minima, cile raya, pesanggrahan",la banda minimarket/cile raya,la banda minimarket,cile raya
299986,299986,"ginzi cafe, siliw,",ginzi cafe/siliwangi,ginzi cafe,siliwangi
299987,299987,jl.jati kramat baru no 1 town house margala,town house margala/jl.jati kramat baru,town house margala,jl.jati kramat baru

In [12]:
train_poi = train[['id', 'raw_address', 'POI']].copy()

In [18]:
train_poi_clean = train_poi.dropna()

In [14]:
train_street = train[['id', 'raw_address', 'street']].copy()

In [19]:
train_street_clean = train_street.dropna()

In [20]:
!pip install spacy

Collecting spacy
  Downloading spacy-3.0.5-cp38-cp38-macosx_10_9_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 357 kB/s eta 0:00:01
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.5-cp38-cp38-macosx_10_9_x86_64.whl (18 kB)
Collecting blis<0.8.0,>=0.4.0
  Downloading blis-0.7.4-cp38-cp38-macosx_10_9_x86_64.whl (5.8 MB)
     |████████████████████████████████| 5.8 MB 162 kB/s eta 0:00:01
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy) (2.24.0)
Collecting pydantic<1.8.0,>=1.7.1
  Downloading pydantic-1.7.3-cp38-cp38-macosx_10_9_x86_64.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 3.4 MB/s eta 0:00:01
Collecting catalogue<2.1.0,>=2.0.1
  Downloading catalogue-2.0.1-py3-none-any.whl (9.6 kB)
Collecting srsly<3.0.0,>=2.4.0
  Downloading srsly-2.4.0-cp38-cp38-macosx_10_9_x86_64.whl (449 kB)
     |████████████████████████████████| 449 kB 2.6 MB/s eta 0:00:01
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.5-cp38-cp38-macosx_10_9_x86_64.whl (31 kB)
Collecting spacy-legacy<3.1.0,>=3.0.0
  Downloading spacy_legacy-3.0.1-py2.py3-none-any.whl (7.0 kB)
Requirement already satisfied: packaging>=20.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy) (20.4)
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.5-cp38-cp38-macosx_10_9_x86_64.whl (105 kB)
     |████████████████████████████████| 105 kB 4.7 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.15.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy) (1.19.2)
Requirement already satisfied: setuptools in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy) (50.3.1.post20201107)
Collecting typer<0.4.0,>=0.3.0
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy) (4.50.2)
Collecting thinc<8.1.0,>=8.0.2
  Downloading thinc-8.0.2-cp38-cp38-macosx_10_9_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 853 kB/s eta 0:00:01
Collecting pathy>=0.3.5
  Downloading pathy-0.4.0-py3-none-any.whl (36 kB)
Requirement already satisfied: jinja2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy) (2.11.2)
Collecting wasabi<1.1.0,>=0.8.1
  Downloading wasabi-0.8.2-py3-none-any.whl (23 kB)
Requirement already satisfied: idna<3,>=2.5 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.0.4)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from packaging>=20.0->spacy) (2.4.7)
Requirement already satisfied: six in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from packaging>=20.0->spacy) (1.15.0)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from typer<0.4.0,>=0.3.0->spacy) (7.1.2)
Collecting smart-open<4.0.0,>=2.2.0
  Downloading smart_open-3.0.0.tar.gz (113 kB)
     |████████████████████████████████| 113 kB 2.6 MB/s eta 0:00:01
Requirement already satisfied: MarkupSafe>=0.23 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from jinja2->spacy) (1.1.1)
Building wheels for collected packages: smart-open
  Building wheel for smart-open (setup.py) ... done
  Created wheel for smart-open: filename=smart_open-3.0.0-py3-none-any.whl size=107095 sha256=4f2b9254d0c60f363cfc5f4bc55bf197a097a593b90a9414107a788bf3cad50d
  Stored in directory: /Users/aanabdurrahman/Library/Caches/pip/wheels/11/73/9a/f91ac1f1816436b16423617c5be5db048697ff152a9c4346f2
Successfully built smart-open
Installing collected packages: murmurhash, blis, pydantic, catalogue, srsly, cymem, spacy-legacy, preshed, typer, wasabi, thinc, smart-open, pathy, spacy
Successfully installed blis-0.7.4 catalogue-2.0.1 cymem-2.0.5 murmurhash-1.0.5 pathy-0.4.0 preshed-3.0.5 pydantic-1.7.3 smart-open-3.0.0 spacy-3.0.5 spacy-legacy-3.0.1 srsly-2.4.0 thinc-8.0.2 typer-0.3.2 wasabi-0.8.2

In [22]:
!python -m spacy download xx_sent_ud_sm

Collecting xx-sent-ud-sm==3.0.0
  Downloading https://github.com/explosion/spacy-models/releases/download/xx_sent_ud_sm-3.0.0/xx_sent_ud_sm-3.0.0-py3-none-any.whl (9.5 MB)
     |████████████████████████████████| 9.5 MB 1.3 MB/s eta 0:00:01
Requirement already satisfied: spacy<3.1.0,>=3.0.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from xx-sent-ud-sm==3.0.0) (3.0.5)
Requirement already satisfied: pathy>=0.3.5 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (0.4.0)
Requirement already satisfied: packaging>=20.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (20.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.24.0)
Requirement already satisfied: pydantic<1.8.0,>=1.7.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (1.7.3)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (3.0.1)
Requirement already satisfied: wasabi<1.1.0,>=0.8.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (0.8.2)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (1.0.5)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (3.0.5)
Requirement already satisfied: typer<0.4.0,>=0.3.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (0.3.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.0.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.4.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (4.50.2)
Requirement already satisfied: jinja2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.11.2)
Requirement already satisfied: thinc<8.1.0,>=8.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (8.0.2)
Requirement already satisfied: setuptools in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (50.3.1.post20201107)
Requirement already satisfied: numpy>=1.15.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (1.19.2)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.0.5)
Requirement already satisfied: blis<0.8.0,>=0.4.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (0.7.4)
Requirement already satisfied: smart-open<4.0.0,>=2.2.0 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from pathy>=0.3.5->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (3.0.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from packaging>=20.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.4.7)
Requirement already satisfied: six in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from packaging>=20.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from requests<3.0.0,>=2.13.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (1.25.11)
Requirement already satisfied: click<7.2.0,>=7.1.1 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from typer<0.4.0,>=0.3.0->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/aanabdurrahman/opt/anaconda3/lib/python3.8/site-packages (from jinja2->spacy<3.1.0,>=3.0.0->xx-sent-ud-sm==3.0.0) (1.1.1)
Installing collected packages: xx-sent-ud-sm
Successfully installed xx-sent-ud-sm-3.0.0
✔ Download and installation successful
You can now load the package via spacy.load('xx_sent_ud_sm')

In [23]:
import spacy

In [24]:
nlp = spacy.blank('id')

In [25]:
nlp?